services:
  app:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    # Need to be host so the container can access the host's network, like connecting to host's browser
    network_mode: host
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules
      - app_next_dir:/app/.next
    command: npm run dev

  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # chrome:
  #   image: ghcr.io/browserless/chromium
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - TOKEN=6R0W53R135510
  #     # - TIMEOUT=60000

  # chrome:
  #   image: kasmweb/chrome:1.16.0
  #   environment:
  #     - VNC_PW=password
  #     - APP_ARGS="--remote-debugging-port=9222 --remote-debugging-address=0.0.0.0"
  #   ports:
  #     - 9222:9222
  #     - 6901:6901

volumes:
  app_node_modules:
  app_next_dir:
  postgres_data:
