import { z } from 'zod'

export const allUfs = [
  'ac',
  'al',
  'am',
  'ap',
  'ba',
  'ce',
  'df',
  'es',
  'go',
  'ma',
  'mg',
  'ms',
  'mt',
  'pa',
  'pb',
  'pe',
  'pi',
  'pr',
  'rj',
  'rn',
  'ro',
  'rr',
  'rs',
  'sc',
  'se',
  'sp',
  'to',
] as const

export const ufLabels: Record<UF, string> = {
  ac: 'Acre',
  al: 'Alagoas',
  am: 'Amazonas',
  ap: 'Amapá',
  ba: 'Bahia',
  ce: 'Ceará',
  df: 'Distrito Federal',
  es: 'Espírito Santo',
  go: 'Goiás',
  ma: 'Maranhão',
  mg: 'Minas Gerais',
  ms: 'Mato Grosso do Sul',
  mt: 'Mato Grosso',
  pa: 'Pará',
  pb: 'Paraíba',
  pe: 'Permanbuco',
  pi: 'Piuaí',
  pr: 'Paraná',
  rj: 'Rio de Janeiro',
  rn: 'Rio Grande do Norte',
  ro: 'Rondônia',
  rr: 'Roraima',
  rs: 'Rio Grande do Sul',
  sc: 'Santa Catarina',
  se: 'Sergipe',
  sp: 'São Paulo',
  to: 'Tocantins',
}

export const ufSchema = z.enum(allUfs)

export type UF = z.infer<typeof ufSchema>
